### ISSUE TITLE
SystemGroup cannot handle groups with spaces

### ISSUE THREAD

**Issue by bluefoxicy** [apple/cups#5041]
In Cups 2.2.0, the following line works in cups-files.conf:

    SystemGroup "a group" sys root

In Cups 2.2.2, `cupsd -t` reports that the file contains errors for any variant:

    SystemGroup "a group" sys root
    SystemGroup 'a group' sys root
    SystemGroup a\ group sys root

**Comment by michaelrsweet** [comment]
First, spaces are not generally supported in UNIX group names - that it ever worked is blind luck...

Second, the code that parses the system groups hasn't changed in over 10 years and *does* support quoted but not backslash escaped values. Both of the quoted SystemGroup definitions should work, as long as "a group" exists as a group. But note that groups in /etc/group cannot contain spaces on Linux and macOS (at least).

Also, what is the exact error message you are seeing?

**Comment by bluefoxicy** [comment]
> First, spaces are not generally supported in UNIX group names

Too bad.  UNIX supports NIS, LDAP, and other information sources which _do_ support spaces, and doesn't generally filter them to replace spaces with another character.  This is one of the few common questions that pops up on forums and mailing lists about configuring CUPS, as much as there are any common questions about configuring CUPS.

> Second, the code that parses the system groups hasn't changed in over 10 years and does support quoted but not backslash escaped values.

Then I'll need to re-examine my set-up.  It works in Ubuntu 16.10 (Cups 2.2.0) but not 17.04 (2.2.2); perhaps it is a distribution issue, or a configuration error on my part.  I'll find out next week.

> Also, what is the exact error message you are seeing?

`cupsd` just exits with code 2, no logs, and no output.

`cupsd -t` says `/etc/cups/cups-files.conf contains errors` and exits.  It works if I remove the quoted group from `cups-files.conf`.

**Comment by michaelrsweet** [comment]
OK, it appears the error messages are going to the system log (since no log file has been opened yet), rather then the standard error... The quotes are being maintained as part of the lookup.

**Comment by michaelrsweet** [comment]
OK, I've committed changes that force logging to stderr when "-t" is used, and improved the logging of SystemGroup errors.

That said, the code (still) does the right thing with quoted strings, so more than likely the issue is that getgrnam() is not finding the named group.

**Comment by OdyX** [comment]
This change makes builds on systems where a system group doesn't exist fail in the testsuite, e.g.:                 ```
--with-system-groups=lpadmin
```

```
FAIL: 35 error messages, expected 33.
E [28/Aug/2017:13:46:06.572986 +0000] Unknown default SystemGroup "lpadmin".
…
```

The two additionnal error messages are due to two occurences of the above error line.

It'd be ideal if CUPS could continue to build (and have its test run) in a clean environment.

**Comment by michaelrsweet** [comment]
@OdyX Please file a new issue for the test suite problems you are having.

**Comment by darkpixel** [comment]
It looks like all that was done was tests and logging were updated, but CUPS still doesn't appear to support groups with spaces.

After a recent Debian update, we have ~40 broken CUPS servers that refuse to start unless we remove "Domain Admins" from SystemGroup.  All these machines interface with Windows AD or Samba for access.

To work around this bug, we had to go through every client site and create a ```cups-admins``` group and add individual users to it.  Simply adding ```Domain Admins``` to the ```cups-admins``` group doesn't work.  I guess cups has trouble resolving nested groups (or nested groups with spaces) too.
