### ISSUE TITLE
Downloaded CUPS 2.2.4

### ISSUE THREAD

**Issue by GVCCbob** [apple/cups#5057]
Downloaded and expanded Folder.

How do I install it so when I launch CUPS I get the newer version.

I do not see an installer in the folder.

Mac Sierra

**Comment by peturbg** [comment]
im on ubuntu server and can't have the latest cups 2.2.4 becouse the developers didn't make .deb executable. I can't compile becouse i don't know how, and second when you compile you don't know where to put what to compile, in this case if i run make i read that if you don't say where it compile in different directory. So this is issue becouse when you need help you will not where cups has been compiled. So ubuntu users protest developers when make new program make executable too and separately source, becouse in the moment we are using 2.2.1 obsolete versions and in this case with ssl problem. If you didn't read, read here that i put this: 
cups 2.2.1 ubuntu Unable to encrypt connection: A TLS fatal alert has been received. and much more problems with cups ubuntu server latest 17.04
https://github.com/apple/cups/issues/5058

I read that this problem is fixed in 2.2.4 so someone can break now in the server and robbery all information. ssl issues are big issues failing be resolved it mean this is not your computer.

**Comment by peturbg** [comment]
hi guys. for this who use linux ditros i find that you can install the latest cups from here: http://ftp.de.debian.org/debian/pool/main/
Now quesitons. why ubuntu has called pool, when they need to call it new release. why ubuntu has put them in pool " in new release " and they directly don't put them that when peoples do apt-get update to tell them they have update, why ubuntu don't tell peoples that there exist pool " new release " that peoples can download and not run obsolete versions.  include A TLS fatal alert has been received. and much more problems with cups ubuntu server latest 17.04 is not fixed in 2.2.4, you need to create /etc/cups/client.conf and put this:
Encryption Required
SSLOptions DenyTLS1.0
whis this two you can open from mobile phone and it will be green bar, but after you enter in another menu, for example admin menu you will see insecure connection and inmediatelly will change on secure connection, now cups need to put http2 i will not tell why, if cups are real developers will know why. now cups come with cheap cypher i like to change cypher and it is not possible. I don't care if cups come with rcdha or ecdha, i want to change cypher like in dovecot. with the now configuration without denytls1.0 it will jump on more cheap cypher and cups can be man in the middle, for that more servers has been broked becouse cups use obsolete and cheap cyphers, what i read a stupid comment or maybe stupid comments from the developers was that cups is like apache or apache2 and this who know apache or apache2 know cups and this is false, cups don't have nothing to do with apache or apache2. So if cups is like apache, then cups use apache version, yes guys you read cups use some apache 1 version, this mean 
cups is insecure, becouse all attack of apache 1 " no apache 1 is not apache 2, apache 1 is apache 1 and apache 2 is the next version of apache " so if attacks had find in apache 1 then attackers can broke in apache 1 and this mean your server is compromised.

**Comment by michaelrsweet** [comment]
@GVCCbob The CUPS source code archive does NOT contain a macOS installer. While you can compile the CUPS source code on macOS, you cannot install it and still have a working system - code signing will prevent many of the system-supplied applications from working due to the changed libraries, and SIP (System Integrity Protection) would need to be disabled to overwrite the supplied libcups and other CUPS binaries. (For various reasons you *can* update programs installed to /usr/libexec/cups...) So sorry, but if you want a newer CUPS you'll need to wait for a macOS update containing a newer version of CUPS...
